<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net9.0-android;net9.0-ios</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net9.0-windows10.0.19041.0</TargetFrameworks>

		<OutputType>Exe</OutputType>
		<RootNamespace>BatiaSuite</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<ApplicationTitle>BatiaSuite</ApplicationTitle>

		<ApplicationId>com.companyname.batiasuite</ApplicationId>
		<ApplicationIdGuid>c32f8002-8c0d-47c2-a53b-d2a8e250d3db</ApplicationIdGuid>

		<ApplicationDisplayVersion>2.9.0</ApplicationDisplayVersion>
		<ApplicationVersion>55</ApplicationVersion>
		<Version>2.9.0</Version>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">12.2</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">13.1</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">23.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>

		<SkipStaticLibraryValidation>true</SkipStaticLibraryValidation>

		<AndroidSigningKeyStore>SuiteBatiaFirma.keystore</AndroidSigningKeyStore>
	</PropertyGroup>

	<PropertyGroup Condition="$(TargetFramework.Contains('-android')) or $(TargetFramework.Contains('-ios')) or $(TargetFramework.Contains('-windows'))">
		<UseMauiMaps>true</UseMauiMaps>
	</PropertyGroup>

	<!--CONFIGURACIÓN CUANDO ESTÁS EN VISUAL STUDIO (DEBUG / DESARROLLO) -->
	<PropertyGroup Condition="'$(TargetFramework)' == 'net9.0-ios' And '$(BuildingInsideVisualStudio)' == 'true' And '$(Configuration)' == 'Debug'">
		<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
		<ServerAddress>192.168.11.33</ServerAddress>
		<ServerUser>ricardoberistain</ServerUser>
		<ServerTcpPort>52852</ServerTcpPort>
		<ApplicationId>com.GrupoBatia.SuiteBatia</ApplicationId>
		<ApplicationTitle>Suite Batia</ApplicationTitle>
		
		<ProvisioningType>manual</ProvisioningType>
		<CodesignKey>Apple Distribution: Jesus Ricardo Beristain Ramos (5AB67MUU5A)</CodesignKey>
		<CodesignProvision>SuiteBatia_AdHoc</CodesignProvision>
		
		<!-- ENTORNO SEGURO PARA NO CRASHEAR EN EL IPHONE -->
		<PublishTrimmed>true</PublishTrimmed>
		<TrimMode>copyused</TrimMode>
		<MtouchLink>None</MtouchLink>
		<UseInterpreter>true</UseInterpreter>
		<MtouchFastDev>false</MtouchFastDev>
		
		<BuildIpa>true</BuildIpa>
		<ArchiveOnBuild>true</ArchiveOnBuild>
	</PropertyGroup>

	<!--CONFIGURACIÓN COMPLETA PARA GENERAR EL ARCHIVE (RELEASE) -->
	<PropertyGroup Condition="'$(TargetFramework)' == 'net9.0-ios' And '$(Configuration)' == 'Release'">
		<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
		<ServerAddress>192.168.11.33</ServerAddress>
		<ServerUser>ricardoberistain</ServerUser>
		<ServerTcpPort>52852</ServerTcpPort>
		<ApplicationId>com.GrupoBatia.SuiteBatia</ApplicationId>
		<ApplicationTitle>Suite Batia</ApplicationTitle>
		
		<ProvisioningType>manual</ProvisioningType>
		<CodesignKey>Apple Distribution: Jesus Ricardo Beristain Ramos (5AB67MUU5A)</CodesignKey>
		<CodesignProvision>SuiteBatia_AppStore</CodesignProvision>
		
		<PublishTrimmed>true</PublishTrimmed>
		<TrimMode>copyused</TrimMode>
		<MtouchLink>None</MtouchLink>
		<UseInterpreter>true</UseInterpreter>
		<EnableAssemblyILStripping>false</EnableAssemblyILStripping>
		<MtouchFastDev>false</MtouchFastDev>
		
		<BuildIpa>true</BuildIpa>
		<ArchiveOnBuild>true</ArchiveOnBuild>
	</PropertyGroup>

	<ItemGroup>
		<MauiIcon Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'" Include="Resources\AppIcon\appiconandroid.svg" ForegroundFile="Resources\AppIcon\appiconfgandroid.svg" />
		<MauiIcon Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) != 'android'" Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" />

		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#53c7e0" BaseSize="200,200" />

		<MauiImage Include="Resources\Images\*" />

		<MauiFont Include="Resources\Fonts\*" />

		<MauiFont Include="Resources\IconFonts\*" />
		<MauiFont Include="Resources\IconFonts\icons.ttf" Alias="Icon fonts family" />

		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>
	<ItemGroup>
		<Compile Remove="Resources\IconFonts\FontAwesome.cs" />
	</ItemGroup>

	<ItemGroup>
		<None Remove="Resources\IconFonts\icons.ttf" />
		<None Remove="Resources\Images\bien.png" />
		<None Remove="Resources\Images\ch_f.png" />
		<None Remove="Resources\Images\ch_t.png" />
		<None Remove="Resources\Images\eye_off.png" />
		<None Remove="Resources\Images\eye_on.png" />
		<None Remove="Resources\Images\logo_correctivos.png" />
		<None Remove="Resources\Images\mal.png" />
		<None Remove="Resources\Images\na.png" />
		<None Remove="Resources\Images\regular.png" />
		<None Remove="Resources\Images\sanitizacion.png" />
		<None Remove="Resources\Images\supervision.png" />
		<None Remove="Resources\Images\vacantes.png" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Resources\IconFonts\icons.ttf" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Camera.MAUI" Version="1.5.1" />
		<PackageReference Include="CommunityToolkit.Maui" Version="9.0.0" />
		<PackageReference Include="CommunityToolkit.Maui.Markup" Version="4.0.0" />
		<PackageReference Include="CommunityToolkit.Maui.MediaElement" Version="4.1.2" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.9" />
		<PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.2" />
		<PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.10" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="$(MauiVersion)" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="8.0.0" />
		<PackageReference Include="Microsoft.Maui.Controls.Maps" Version="9.0.120" />
		<PackageReference Include="Microsoft.Maui.Essentials" Version="9.0.120" />
		<PackageReference Include="Mopups" Version="1.3.1" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="Plugin.LocalNotification" Version="12.0.2" />
		<PackageReference Include="PropertyChanged.Fody" Version="4.1.0" />
		<PackageReference Include="Shiny.Core" Version="3.3.4" />
		<PackageReference Include="Shiny.Framework" Version="4.1.0" />
		<PackageReference Include="Shiny.Hosting.Maui" Version="3.3.4" />
		<PackageReference Include="Shiny.Jobs" Version="3.3.4" />
		<PackageReference Include="Shiny.Locations" Version="3.3.4" />
		<PackageReference Include="SlackAPI" Version="1.1.14" />
		<PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
		<PackageReference Include="SQLitePCLRaw.core" Version="3.0.2" />
		<PackageReference Include="SQLitePCLRaw.provider.e_sqlite3" Version="3.0.2" />
	</ItemGroup>

	<ItemGroup Condition="$(TargetFramework.Contains('-android'))">
		<PackageReference Include="Xamarin.AndroidX.LocalBroadcastManager" Version="1.1.0.22" />
		<PackageReference Include="Xamarin.AndroidX.Lifecycle.LiveData.Core" Version="2.8.7.3" />
		<PackageReference Include="Xamarin.AndroidX.Lifecycle.LiveData" Version="2.8.7.3" />
		<PackageReference Include="Xamarin.AndroidX.Lifecycle.Runtime" Version="2.8.7.3" />
		<PackageReference Include="Xamarin.AndroidX.Lifecycle.Runtime.Ktx.Android" Version="2.8.7.3" />
		<PackageReference Include="Xamarin.AndroidX.Lifecycle.ViewModel" Version="2.8.7.3" />
		<PackageReference Include="Xamarin.AndroidX.Lifecycle.ViewModelSavedState" Version="2.8.7.3" />
	</ItemGroup>
	
	<ItemGroup Condition="$(TargetFramework.Contains('-android'))">
		<PackageReference Include="Xamarin.AndroidX.Lifecycle.Common" Version="2.9.2.1" />
		<PackageReference Include="Xamarin.AndroidX.Lifecycle.Runtime" Version="2.9.2.1" />
		<PackageReference Include="Xamarin.AndroidX.Lifecycle.ViewModelSavedState" Version="2.9.2.1" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Controls\OptionsViewMantenimiento.xaml.cs">
			<DependentUpon>OptionsViewMantenimiento.xaml</DependentUpon>
		</Compile>
		<Compile Update="Popups\AgregarProductoPopup.xaml.cs">
			<DependentUpon>AgregarProductoPopup.xaml</DependentUpon>
		</Compile>
		<Compile Update="Popups\MatSumClientePopup.xaml.cs">
			<DependentUpon>MatSumClientePopup.xaml</DependentUpon>
		</Compile>
		<Compile Update="Popups\LocationUsePopup.xaml.cs">
			<DependentUpon>LocationUsePopup.xaml</DependentUpon>
		</Compile>
		<Compile Update="Popups\VersionApp\VersionAppPopup.xaml.cs">
			<DependentUpon>VersionAppPopup.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\CheckListAparadores\CheckListAparadoresPreguntasResumenPage.xaml.cs">
			<DependentUpon>CheckListAparadoresPreguntasResumenPage.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\CheckListAparadores\CheckListAparadoresPreguntasDosPage.xaml.cs">
			<DependentUpon>CheckListAparadoresPreguntasDosPage.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\CheckListAparadores\CheckListAparadoresPreguntasCuatroPage.xaml.cs">
			<DependentUpon>CheckListAparadoresPreguntasCuatroPage.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\CheckListAparadores\CheckListAparadoresPreguntasCincoPage.xaml.cs">
			<DependentUpon>CheckListAparadoresPreguntasCincoPage.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\CheckListAparadores\CheckListAparadoresPreguntasTresPage.xaml.cs">
			<DependentUpon>CheckListAparadoresPreguntasTresPage.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\CheckListAparadores\CheckListAparadoresPreguntasUnoPage.xaml.cs">
			<DependentUpon>CheckListAparadoresPreguntasUnoPage.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\CheckListAparadores\CheckListAparadoresInmueblePage.xaml.cs">
			<DependentUpon>CheckListAparadoresInmueblePage.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\DeliveriesRoute.xaml.cs">
			<DependentUpon>DeliveriesRoute.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\EntregasInteligentes\EntregasInteligentesPage.xaml.cs">
			<DependentUpon>EntregasInteligentesPage.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\IncidenciasBiometa\IncidenciasBiometaPage.xaml.cs">
			<DependentUpon>IncidenciasBiometaPage.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\OrdenesTrabajo\GenerarOrdenTrabajo.xaml.cs">
			<DependentUpon>GenerarOrdenTrabajo.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\SolicitudCotizacion\SolicitudCotizacionPage.xaml.cs">
			<DependentUpon>SolicitudCotizacionPage.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\SupervisionMantenimiento\SupervisionMantenimientoFirmasPage.xaml.cs">
			<DependentUpon>SupervisionMantenimientoFirmasPage.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\SupervisionMantenimiento\SupervisionMantenimientoEvaluacionPage.xaml.cs">
			<DependentUpon>SupervisionMantenimientoEvaluacionPage.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\SupervisionMantenimiento\SupervisionMantenimientoExtintoresObjectPage.xaml.cs">
			<DependentUpon>SupervisionMantenimientoExtintoresObjectPage.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\SupervisionMantenimiento\SupervisionMantenimientoHidrantesObjectPage.xaml.cs">
			<DependentUpon>SupervisionMantenimientoHidrantesObjectPage.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\SupervisionMantenimiento\SupervisionMantenimientoSeccionPage.xaml.cs">
			<DependentUpon>SupervisionMantenimientoSeccionPage.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\SupervisionMantenimiento\SupervisionMantenimientoSeccionesPage.xaml.cs">
			<DependentUpon>SupervisionMantenimientoSeccionesPage.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\SupervisionMantenimiento\SupervisionMantenimientoPreguntasPage.xaml.cs">
			<DependentUpon>SupervisionMantenimientoPreguntasPage.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\SupervisionMantenimiento\SupervisionMantenimientoInmueblePage.xaml.cs">
			<DependentUpon>SupervisionMantenimientoInmueblePage.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\SupervisionMantenimiento\SupervisionMantenimientoPage.xaml.cs">
			<DependentUpon>SupervisionMantenimientoPage.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\Supervision\EvaluacionPage.xaml.cs">
			<DependentUpon>EvaluacionPage.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\Supervision\VideoPage.xaml.cs">
			<DependentUpon>VideoPage.xaml</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<MauiXaml Update="Controls\BordererDatePicker.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Controls\BordererEditor.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Controls\BordererEntry.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Controls\BordererLabel.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Controls\BordererPicker.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Controls\CheckBoxView.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Controls\CustomCheckBox.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Controls\ItemView.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Controls\MasterPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Controls\OptionsViewMantenimiento.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Controls\OptionsView.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Controls\RadioButtonEncuesta.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Popups\AlmacenPicker.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Popups\AgregarProductoPopup.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Popups\MaterialPicker.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Popups\MatSumClientePopup.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Popups\ObjectPicker.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Popups\PersonalPicker.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Popups\LocationUsePopup.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Popups\RutasEntregas\ConfirmarInicioRutaPopup.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Popups\VersionApp\VersionAppPopup.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Resources\Styles\Converters.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Resources\Styles\Resources.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\CheckListAparadores\CheckListAparadoresPreguntasResumenPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\CheckListAparadores\CheckListAparadoresPreguntasDosPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\CheckListAparadores\CheckListAparadoresPreguntasCuatroPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\CheckListAparadores\CheckListAparadoresPreguntasCincoPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\CheckListAparadores\CheckListAparadoresPreguntasTresPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\CheckListAparadores\CheckListAparadoresPreguntasUnoPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\CheckListAparadoristasAldoConti\AparadoristasPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\ChecklistLimpieza\LimpiezaPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\ChecklistMantenimiento\MantenimientoPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\ChecklistMonitoreo\MonitoreoPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\CheckListSupervisionesAldoConti\ChecklistPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\CorrectivosMayoresPages\CorrectivosPendientesBanner.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\DeliveriesRoute.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\Deliveries.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\DeliveriesDetail.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\DiarioGerenteAldoConti\DiarioGerentePage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\DiarioLimpieza\DiarioLimpiezaPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\Encuestas\EncuestaPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\EntregasInteligentes\EntregasInteligentesPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\IncidenciasBiometa\IncidenciasBiometaPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\ListaCorrectivosM.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\ListadoMateriales.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\ListasOrdenesTGuardadas.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\Logueo.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\NotificacionesSupervisores\CentroNotificacionesSupervisor.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\OrdenesTrabajo\FotoEvidenciaPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\OrdenesTrabajo\ManoObra.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\OrdenesTrabajo\MaterialesUtilizados.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\OrdenesTrabajo\GenerarOrdenTrabajo.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\OrdenesTrabajo\OrdenTrabajo.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\RegisterDelivery.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\RegistrosCorrctivosM.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\ReporteMantenimientoAldoConti\ReporteMantenimientoPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\RutasEntregas\TiposListadoPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\Sanitizacion\EvidenciasPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\Sanitizacion\SanitizacionPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\SolicitudCotizacion\SolicitudCotizacionPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\CheckListAparadores\CheckListAparadoresInmueblePage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\SupervisionMantenimiento\SupervisionMantenimientoFirmasPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\SupervisionMantenimiento\SupervisionMantenimientoEvaluacionPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\SupervisionMantenimiento\SupervisionMantenimientoExtintoresObjectPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\SupervisionMantenimiento\SupervisionMantenimientoHidrantesObjectPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\SupervisionMantenimiento\SupervisionMantenimientoSeccionPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\SupervisionMantenimiento\SupervisionMantenimientoSeccionesPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\SupervisionMantenimiento\SupervisionMantenimientoPreguntasPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\SupervisionMantenimiento\SupervisionMantenimientoInmueblePage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\SupervisionMantenimiento\SupervisionMantenimientoPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\Supervision\ChecklistOperadorPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\Supervision\EncuestaSupervisionPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\Supervision\VideoPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\Supervision\MaterialesPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\Supervision\EvaluacionPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\Supervision\PreguntasPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\Supervision\SupervisionInmueblePage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\Supervision\SupervisionPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\SupplierDeliveries\SupplierDeliveries.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\SupplierDeliveries\SupplierDeliveriesDetail.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\SupplierDeliveries\SupplierListadoMateriales.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\SupplierDeliveries\SupplierRegisterDelivery.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\Vacantes\DatosComplementariosPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\Vacantes\DatosGeneralesPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\Vacantes\DatosSueldoPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\Vacantes\DireccionFiscalPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\Vacantes\DireccionPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\Vacantes\DocumentosPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\Vacantes\VacantesPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
	</ItemGroup>

	<ProjectExtensions>
		<VisualStudio>
			<UserProperties XamarinHotReloadDebuggerTimeoutExceptionBatiaSuiteHideInfoBar="True" XamarinHotReloadGenericExceptionInfoBarBatiaSuiteHideInfoBar="True" />
		</VisualStudio>
	</ProjectExtensions>

</Project>